### ISSUE TITLE
Invalid page token on get_playlist_items(count=None) 

### ISSUE THREAD

**Issue by marco97pa** [sns-sdks/python-youtube#100]
Sometimes by running:  
`playlist = api.get_playlist_items(playlist_id=playlist_id, count=None)`

I get the following exception:
`pyyoutube.error.PyYouTubeException: YouTubeException(status_code=400,message=The request specifies an invalid page token.)`

I have a script that runs this line of code every 10 minutes and it happens to break at least 4 times per hour.
It tries to get data from the same playlist so results should be the same, unless a new video is added to that playlist. 
Sometimes I get that error, sometimes it works just fine.
This issue started to happen a week ago on my end. I never experienced similar issues before.

**Comment by z1lc** [comment]
Seeing the same thing, code was running via cron every day without a problem and then a few days ago started seeing this same exception. First time I saw it was on August 13, 2021 01:01am UTC.

The specific calls for me that caused an error:

`GET https://www.googleapis.com/youtube/v3/playlistItems?playlistId=UUn8zNIfYAQNdrFRrr8oibKw&part=contentDetails%2Csnippet&maxResults=50&key=REDACTED&pageToken=CMIDEAA [200, OK]`
`GET https://www.googleapis.com/youtube/v3/playlistItems?playlistId=UUn8zNIfYAQNdrFRrr8oibKw&part=contentDetails%2Csnippet&maxResults=50&key=REDACTED&pageToken=CPQDEAA [400, Bad Request]`

**Comment by z1lc** [comment]
In case it helps, this exception seems to be more likely to occur if the playlist has a significant amount of videos in it. Here's the lengths of the individual playlists for which this error did & did not occur:

```
7658 errored
4498 errored
3470 errored
2114 errored
1683 errored
679 errored
409 no error
316 errored
308 errored
296 errored
280 no error
268 no error
268 no error
155 no error
153 no error
24 no error
7 no error
```

**Comment by marco97pa** [comment]
> Seeing the same thing, code was running via cron every day without a problem and then a few days ago started seeing this same exception. First time I saw it was on August 13, 2021 01:01am UTC.
> 
> The specific calls for me that caused an error:
> 
> `GET https://www.googleapis.com/youtube/v3/playlistItems?playlistId=UUn8zNIfYAQNdrFRrr8oibKw&part=contentDetails%2Csnippet&maxResults=50&key=REDACTED&pageToken=CMIDEAA [200, OK]`
> `GET https://www.googleapis.com/youtube/v3/playlistItems?playlistId=UUn8zNIfYAQNdrFRrr8oibKw&part=contentDetails%2Csnippet&maxResults=50&key=REDACTED&pageToken=CPQDEAA [400, Bad Request]`

Thanks for the comment. I was not sure if it was only a issue on my implementation, but now we are sure that it is happening in different situations.

I can confirm that the issue started on 13 of August 2021

**Comment by marco97pa** [comment]
On my end the issue seems solved since **19:46 CEST, August 17 2021**.  
I already executed **26** calls of `playlist = api.get_playlist_items(playlist_id=playlist_id, count=None)` without any exception.  
I think it was a bad response from the YouTube servers and now it has been solved.
I will test it (one call every 15 minutes) for some days and mark the issue as closed if it will continue to work as expected.

**Comment by z1lc** [comment]
Same here, my most recent run succeeded for all the cases I posted above.

**Comment by MerleLiuKun** [comment]
Hey guys.

Yes, In my projects also has this error, Maybe this is bug for YouTube services. 

We can keep some time for this.

**Comment by marco97pa** [comment]
After more than 24 hours and more than 200 calls succeeded, I can confirm that the issue has been resolved

**Comment by Urkchar** [comment]
This issue is still happening for me. I got the error message on 2021-08-18 14:20:41,112. 
```
Traceback (most recent call last):
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 480, in call_api_until_success
    resp = callable(**kwargs)
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 89, in get_playlist_items
    res_data = self.paged_by_page_token(
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 136, in paged_by_page_token
    data = self._parse_response(resp)  # origin response
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\YouTube Channels Bot\main.py", line 182, in _parse_response
    raise PyYouTubeExceptionDebug(response)
PyYouTubeExceptionDebug: YouTubeException(status_code=400,message=The request specifies an invalid page token.)
```
For what it's worth, this happened on a playlist with lots of videos as mentioned by @z1lc . 
I am using python-youtube version 0.8.1
If you need more information from me, please let me know.
